# Мини-домашка 3

За основу взята [разминочная домашка](https://github.com/iad-24/seminars) с курса ИАД.

In [25]:
import numpy as np

В конце каждого семестра каждый семинарист сталкивается с необходимостью выставить студентам накопленную оценку. Часто семинаристы делают это с помощью Excel или GoogleSheets, но, поверьте, с этим возникают проблемы. В задании вам надо помочь семинаристу выполнить эту непростую работу с помощью `numpy` :)

Выполните ячейку ниже, чтобы загрузить данные и визуально проверить корректность их считывания.

По строкам - студенты, по столбцам - их оценки. В курсе семинарист провел три проверочных (первые три колонки), выдал три домашних работы (следующие три колонки), кроме того, у студентов есть оценка за коллоквиум (последняя колонка).

In [26]:
marks = np.loadtxt("https://raw.githubusercontent.com/iad-24/seminars/master/materials/data_sem1_hw.txt")

In [27]:
marks[:3]

array([[ 7. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 3. ,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ]])

### [1] Число студентов
Сколько студентов в группе семинариста?

In [28]:
### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ

marks.shape[0] # просто нашли число строчек

28

### [2] Очень сложная проверочная, или просто добрый семинарист

Семинарист помнит, что первая проверочная получилась очень сложной, и максимальный балл в группе был далеко не 10. Поэтому он решил поделить баллы за эту проверочную на максимум по группе - чтобы у студента с максимальной оценкой получилось 10, а у остальных - просто оценка больше.

Каков максимальный балл за первую проверочную? Положите ответ в переменную `max_mark`.

In [29]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ люмус

# вытащили первый столбец и нашли в нём максимум
max_mark = marks[:,0].max()
max_mark

7.0

Разделите первый столбец на `max_mark` (для этого надо выделить столбец, поставить после соответствующего выражения знак = и присвоить новое значение столбца)

In [30]:
### ╰( ͡° ͜ʖ ͡° )つ──☆  ридикулус

# сделали подмену :3 
marks[:,0] = 10*marks[:,0]/max_mark

### [2] Подсчет накопленной оценки

Для вычисления накопленной надо посчитать средние оценки за проверочные для каждого студента и средние за домашние работы (может пригодиться `np.mean`). Накопленная оценка есть $0.3 \cdot \text{Проверочные} + 0.4 \cdot \text{Домашние} + 0.3 \cdot \text{Коллоквиум}$. Вычислите накопленные оценки и добавьте их в последний столбец матрицы.

In [31]:
# Веса следует брать из переменной weights, а не вписывать вручную
weights = [0.3, 0.4, 0.3]

In [46]:
marks.shape  # для асистентов, размерность была 7

(28, 7)

In [43]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ экспелярмус

itog = weights[0] * marks[:,:3].mean(axis=1) + weights[1] * marks[:,3:6].mean(axis=1) + weights[2] * marks[:,6]
new_mark = np.hstack((marks, itog[:,np.newaxis]))

In [44]:
new_mark.shape # для асистентов, появился новый столбик

(28, 8)

In [49]:
# Можно вставить и другими способами, например: 
np.insert(marks, 7, itog, axis=1).shape

(28, 8)

In [50]:
marks = np.insert(marks, 7, itog, axis=1)

### [1] Студенты, которых, вероятно, отчислят

Сколько в группе студентов с накопленной оценкой 0? Вам может понадобиться тот факт, что применение np.sum к бинарному вектору дает число значений True в нем, например:

In [51]:
np.sum([True, False, True]) # 2 значения True

2

In [53]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ империо

np.sum(itog == 0)

3

Оцените вероятность того, что студента отчислят. 

In [54]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ круцио

# число нулевых делить на всех
np.sum(itog == 0)/ itog.size

0.10714285714285714

### [1] Студенты, которые получат автоматы
Выделите в отдельный массив студентов, у которых накопленная оценка больше $8$

In [55]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ асцендио

nice_students = itog[itog > 8]
nice_students

array([8.23857143, 9.2       , 8.96380952, 9.46761905, 8.56333333,
       9.21809524, 8.71714286, 8.63428571, 9.96      , 8.51714286,
       9.78857143, 9.56666667, 9.01190476, 8.81666667])

Какова вероятность того, что студент получит автомат?

In [56]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ диссендиум

# студенты с накопом больше 8 делятся на всех
sum(itog > 8)/itog.size

0.5

### [2] Сложность заданий 

Наконец, семинарист хочет оценить сложность заданий, проверочных и коллоквиума по своей особой системе. Он присвоил каждому студенту вес (веса суммируются в 1) и хочет посчитать для каждого задания, проверочной и коллоквиума среднюю оценку с весами. 

Пример, что имеется в виду: если есть $4$ студента с весами `[0.1, 0.2, 0.3, 0.4]` и оценками `[3, 7, 9, 10]`, то средняя оценка за задание с весами получится 

In [57]:
0.1 * 3 + 0.2 * 7 + 0.3 * 9 + 0.4 * 10 

8.4

Веса:

In [61]:
weights = np.array([1.]*7+[2.]*4+[3.]*7+[4.]*(marks.shape[0]-18))

# разделите веса на их сумму, чтобы они суммировались к 1
weights = weights/weights.sum()
weights

array([0.01315789, 0.01315789, 0.01315789, 0.01315789, 0.01315789,
       0.01315789, 0.01315789, 0.02631579, 0.02631579, 0.02631579,
       0.02631579, 0.03947368, 0.03947368, 0.03947368, 0.03947368,
       0.03947368, 0.03947368, 0.03947368, 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158, 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158])

Посчитайте указанным образом сложность каждого "столбца".

In [65]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ авада кедавра

# Например, можно посчитать вот так, задание 3 оч сложное :3 
weights.dot(marks)

array([4.90037594, 7.11973684, 7.85789474, 6.16447368, 4.83289474,
       5.87894737, 4.87368421, 5.70008145])

### [1]  Близость 

Семинаристу стало интересно, какой из студентов ближе всего по своим баллам находится к самому первому. Чтобы выяснить это, он решил посчитать между первым студентом и всеми остальными манхэттенское расстояние. 

Найдите номер студента, для которого расстояние до первого студента является кратчайшим. 

In [77]:
### ╰( ͡° ͜ʖ ͡° )つ──☆ остолбеней

from numpy.linalg import norm

R = norm(marks - marks[0,:], ord=1, axis=1)
R # матрица расстояний

array([ 0.        , 27.3       , 43.42285714, 35.2352381 , 17.98047619,
       40.57      , 39.46238095, 21.23      , 46.5947619 , 53.33333333,
       14.13571429, 46.97380952, 35.13      , 43.71571429, 41.26142857,
       20.39      , 44.53      , 17.62095238, 35.13      , 19.4       ,
       35.13      , 38.51571429, 44.87285714, 41.73666667, 24.38333333,
       18.81      , 47.39619048, 45.88666667])

In [78]:
R.argmax() # номер студента

9

In [76]:
# проверка себя
norm(marks[-1,:] - marks[0,:], ord=1)

45.88666666666667

# Обратная связь

Задачи закончились! После выполнения и до отправки просьба оставить обратную связь по мини-домашке:

https://forms.gle/jZLPK1v4qke4B5QC8