# Семинар 3: Introduction to Data Science 

Сегодня мы поговорим про основы математики, которая нам пригодится для решения задачек по анализу данных. Сегодня в программе: 

* Что такое вероятность и математическое ожидание
* Расстояния между векторами
* Матрицы 

Добро пожаловать подкат. 

## 1. Вероятность

Совсем немного поговорим про вероятности. 

__Ручные упражнения:__

* Драгомир принёс на пару кубик и подкинул его. Какова вероятность того, что на кубике выпадет число $6$? Какова вероятность того, что на кубике выпадет чётное число? 
* Витя очень классный! Маша записала в столовой его номер телефона на салфетке. К сожалению, последние две цифры затёрлись. Маша помнит, что одни из цифр в конце ноль, а вторая нечётная. Какова вероятность, что Маша наберёт правильный телефон с первого раза? 
* Добрыня, Илья и Алёша приехали на пару на кирпич и зашли в лифт. Лифт не сломался и едет наверх. В кирпиче $20$ этажей. Какова вероятность, что парни выйдут на одном этаже? Какова вероятность, что парни выйдут на разных этажах? Какова вероятность, что двое из них выйдут на одном этаже (__подсказка:__ в сумме эти три вероятности дают один). 
* __Задача, которой на самом первом собеседовании по телефону в Яндекс HR проверяют, надо ли бросить трубку.__  Монетку подбросили $5$ раз. Какова вероятность, что орёл на ней выпадет все пять раз? Какова вероятность того, что орёл выпал один раз, а решка $4$ раза?


Ну и ещё совсем немного про математическое ожидание. 

* Дима участвует в лотерее. Он знает, что на $20000$ билетов всего $1$ выигрышный. Дима участвует в игре каждую неделю. Билет стоит $100$ рублей. Выиграть можно $1000000$ рублей. Найдите ожидаемые доходы (или убытки) Димы. 

## 2.  Вектора и расстояния

Война за железный трон спустилась на 7 королевств. Армия Станиса Баратеона остановилась в крепости Драконий Камень. Армия Тайвина Ланистера стоит в разрушенной крепости Харренхолле. Армия Роба Старка оказалась в лесу. Единственному истинному королю и наследнику трона Станису Баратеону нужно решить по кому нанести удар. К счастью у него в свите оказалась леди Мелисандра, знакомая с математикой. 

Красная женщина начертила огнём в воздухе систему координат и выяснила, что в ней Станис находится в точке $A(1,1)$. Ланистеры в точке $B(2,2)$. Старки в точке $C(3,0)$. Бог Света предлагает Станису использовать для поиска расстояния евклидову метрику. До чьей армии ближе идти, чтобы атаковать? 

Старые боги предлагают Станису использовать манхеттенскую метрику для поиска расстояния. До кого ближе идти, чтобы атаковать?  Каких богов вы бы послушали и почему? 

Работать с матрицами и векторам позволяет пакет `numpy`. Подгружаем его.

In [1]:
import numpy as np

Вектора можно вбивать вот так.

In [2]:
a = np.array([1,1])
b = np.array([2,2])
c = np.array([3,0])

b - a

array([1, 1])

In [3]:
(b - a)**2

array([1, 1])

In [4]:
np.sum((b - a)**2)

2

In [5]:
np.sqrt(np.sum((b - a)**2))

1.4142135623730951

Такое расстояние называется евклидовым или $l_2$ нормой. __Физический смысл:__ кратчайшее расстояние между двумя точками.

$\ell_{2}$ норма (также известная как евклидова норма)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

In [6]:
from numpy.linalg import norm

norm(b - a, ord=2)

1.4142135623730951

Другой вариант - посчитать манхэттенское расстояние или $l_1$ норму. __Физический смысл:__ расстояние, если мы идём по городским кварталам.

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

In [7]:
b - a

array([1, 1])

In [8]:
np.abs(b - a)

array([1, 1])

In [9]:
np.sum(np.abs(b - a))

2

Какую метрику для поиска расстояния между точками $A$ и $B$ вы бы использовали в ситуациях ниже? 

<img src="https://raw.githubusercontent.com/FUlyankin/HSE_Data_Culture/master/nda/images/metr_2.png" width="400"> 

<img src="https://raw.githubusercontent.com/FUlyankin/HSE_Data_Culture/master/nda/images/metr_1.png" width="400"> 



## 3. Матрицы и вектора 

Нам нужны данные. Таблички, в которых лежат данные обычно называют __матрицами.__ Давайте заведём себе такую. 

Задаём ребятам вопросы! Заводим массив по итогам коллективного ответа на вопросы (строки - вопросы, столбцы - число ответов "да", "нет", "воздержался":

In [10]:
l= [[30, 2, 0],
    [3, 27, 1], 
    [28, 1, 1], 
    [6, 17, 5]]

X = np.array(l)

X

array([[30,  2,  0],
       [ 3, 27,  1],
       [28,  1,  1],
       [ 6, 17,  5]])

Узнаём размерность матрицы.

In [11]:
X.shape

(4, 3)

Число полученных ответов на вопросы.

In [12]:
np.sum(X)

121

Что будет, если сложить все числа по столбцам?

In [13]:
X.sum(axis=1, keepdims=True)

array([[32],
       [31],
       [30],
       [28]])

In [14]:
X.sum(axis=1)

array([32, 31, 30, 28])

In [15]:
# без keepdims размерность будет (4,)
X.sum(axis=1).shape

(4,)

А если по строкам?

In [16]:
X.sum(axis=0)

array([67, 47,  7])

Давайте попробуем посчитать сумму по строкам через произведение матриц.

In [17]:
ones = np.ones(3) # завели вектор из единиц
ones  

array([1., 1., 1.])

In [18]:
np.dot(X, ones)

array([32., 31., 30., 28.])

Кто может на доске написать расписать мне, что сейчас произошло? :) 

### Индексация

Для индексации ставим [ ] и через запятую перечисляем действия с осями. В матрице 0 - по вертикали, 1 - по горизонтали

In [19]:
X[2, 1] # выбрать 1 элемент

1

In [20]:
X[:, 2] # выделить столбец

array([0, 1, 1, 5])

In [21]:
X[:, -1] # выделить последний столбец

array([0, 1, 1, 5])

In [22]:
X[1] # выделить строку

array([ 3, 27,  1])

In [23]:
X[:, ::2] # выделить все столбы с четными номерами

array([[30,  0],
       [ 3,  1],
       [28,  1],
       [ 6,  5]])

### Добавление оси

In [24]:
ones[:, np.newaxis]

array([[1.],
       [1.],
       [1.]])

In [25]:
ones[:, np.newaxis].shape 
# вместо вектора с формой (3,) стала матрциа с формой (3, 1)

(3, 1)

In [26]:
ones[np.newaxis, :]
# вместо вектора с формой (3,) стала матрциа с формой (1, 3)

array([[1., 1., 1.]])

In [27]:
ones[np.newaxis, :].shape

(1, 3)

Добавляем в таблицу новый вопрос в таблицу

In [28]:
row = np.array([5, 12, 15])
row = row[np.newaxis, :] 

# конкретно тут можно без увеличения размерности
# но в других случаях может быть ошибка, лучше добавлять
X = np.vstack((X, row))
X

array([[30,  2,  0],
       [ 3, 27,  1],
       [28,  1,  1],
       [ 6, 17,  5],
       [ 5, 12, 15]])

Добавляем новый столбец в таблицу - максимальное число ответов

In [29]:
mx = np.max(X, axis = 1)
mx

array([30, 27, 28, 17, 15])

In [30]:
mx.shape

(5,)

In [31]:
mx = mx[:, np.newaxis]
mx.shape

(5, 1)

In [32]:
X = np.hstack ((X, mx))
X

array([[30,  2,  0, 30],
       [ 3, 27,  1, 27],
       [28,  1,  1, 28],
       [ 6, 17,  5, 17],
       [ 5, 12, 15, 15]])

Удаление строки (аналогично можно удалять столбец):

In [33]:
np.delete(X, np.arange(3, 5), axis=0)

array([[30,  2,  0, 30],
       [ 3, 27,  1, 27],
       [28,  1,  1, 28]])

Ещё один способ создать массив.

In [34]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1, 10, 3)

array([1, 4, 7])

Выделяем строки, у которых ответов "нет" больше, чем ответов "да"

In [36]:
no = X[:, 1]
yes = X[:, 0]
mask = no > yes
mask

array([False,  True, False,  True,  True])

In [37]:
X[mask, :]

array([[ 3, 27,  1, 27],
       [ 6, 17,  5, 17],
       [ 5, 12, 15, 15]])

In [38]:
X[mask] # можно без второго :

array([[ 3, 27,  1, 27],
       [ 6, 17,  5, 17],
       [ 5, 12, 15, 15]])

### Поэлементные операции

Все операции применяются поэлементно, для этого нужно, чтобы форма массивов была одинаковой (допускается размерность 1 вместо какой-то большей, тогда число в этой позиции повторяется до нужного количества)

In [39]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

In [40]:
a + b  # поэлементное сложение

array([4, 4, 4])

In [41]:
a * b  # поэлементное умножение

array([3, 4, 3])

In [42]:
a**2   # поэлементно возвелись в квадрат

array([1, 4, 9])

In [43]:
2*a    # все числа умножились на два

array([2, 4, 6])

### Скалярное произведение и умножение матриц

Поговорим теперь про скалярное произведение и перемножение матриц. 

Скалярное произведение в пространстве $\mathbb{R}^{n}$ для двух векторов $x = (x_{1}, \dots, x_{n})$ и $y = (y_{1}, \dots, y_{n})$ определяется как:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$


Пусть в векторе $q$ записано количество проданных булочек. В векторе $p$ их цены. Что тогда нам даст скалярное произведение? __Распишите на доске руками.__

In [44]:
q = np.array([2, 10, 5])
p = np.array([1, 9, 3])

In [45]:
np.dot(p, q)

107

In [46]:
p.dot(q)

107

А теперь с матрциами! В первой матрице - цены булочек в рублях и в долларах, во второй число проданных булочек в разных киосках. Что получается при перемножении матриц?  __Распишите на доске руками.__

In [47]:
q = np.array([[2, 10, 5],[3, 1, 8]])
p = np.array([[1, 9, 3], [5, 5, 5]])

In [48]:
q

array([[ 2, 10,  5],
       [ 3,  1,  8]])

In [49]:
q.T  # транспонирование

array([[ 2,  3],
       [10,  1],
       [ 5,  8]])

In [50]:
np.dot(p, q.T)

array([[107,  36],
       [ 85,  60]])

In [51]:
p.dot(q.T)

array([[107,  36],
       [ 85,  60]])

## 4. Генерация случайных чисел

In [52]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.random.choice(a, size=5, replace=False)

array([1, 9, 2, 6, 3])

In [54]:
np.random.choice(a, size=5, replace=True)

array([3, 1, 4, 3, 9])

In [55]:
np.random.normal(loc=1, scale=4, size=2)

array([6.49322249, 9.34537801])

In [56]:
np.random.normal(loc=1, scale=4, size=(2,2))

array([[-4.2493951 ,  2.94154346],
       [ 0.73793239, -0.18158946]])

In [57]:
np.random.normal(loc=1, scale=4, size=(2,2,2))

array([[[-3.06212432,  4.19777122],
        [-1.07948377,  4.9577684 ]],

       [[ 5.12640287, -1.89463516],
        [-7.51008004,  7.84719242]]])