# Numpy

In [1]:
# импортировать библиотеку `numpy` под псевдонимом `np`

import numpy as np

In [2]:
# Посчитать массив C как сумму соответствующих элементов A & B

A = np.array([1,-10,3,0,1,75,3])
B = np.array([9,1,567,1,4557,1123,1])
A + B

array([  10,   -9,  570,    1, 4558, 1198,    4])

In [3]:
# Умножить все элементы массива B на 1/3

B * (1/3)

array([3.00000000e+00, 3.33333333e-01, 1.89000000e+02, 3.33333333e-01,
       1.51900000e+03, 3.74333333e+02, 3.33333333e-01])

In [4]:
# создать двумерный массив `B` из списка `A` и сохранить его в файл `./saved_array_B.npy`

A = [[8,   0,  -3,  -7,   9, -10,  -7,  -7],
     [-5,   5,   0,   9,  -5,  -8,  -9,   0],
     [9,   7,  -3,  -4,   3,  -1,   0,  -3],
     [1,   3,   3,   9,   4,  -5,   6,   6],
     [-2,   2,   3,   8,   6,  -2,   5,  -2]]

B = np.array(A)
np.save('saved_array_B', B)

In [5]:
# Загрузить массив B и вывести его, чтобы убедиться, что все верно прочиталось

np.load('saved_array_B.npy')

array([[  8,   0,  -3,  -7,   9, -10,  -7,  -7],
       [ -5,   5,   0,   9,  -5,  -8,  -9,   0],
       [  9,   7,  -3,  -4,   3,  -1,   0,  -3],
       [  1,   3,   3,   9,   4,  -5,   6,   6],
       [ -2,   2,   3,   8,   6,  -2,   5,  -2]])

In [6]:
# Вывести размерность массива B

B.shape

(5, 8)

In [7]:
# В массиве В найти сумму всех элементов, какую вы ожидаете размерность выхода?

B.sum()

23

In [8]:
# В массиве В найти сумму по строкам, какую вы ожидаете размерность выхода?

B.sum(1)

array([-17, -13,   8,  27,  18])

In [9]:
# В массиве В найти сумму по столбцам, какую вы ожидаете размерность выхода?

B.sum(0)

array([ 11,  17,   0,  15,  17, -26,  -5,  -6])

In [10]:
# Вывести все эл-ты предпоследнего столбца

B[:, -1]

array([-7,  0, -3,  6, -2])

In [11]:
# Вывести с 3го по 6ой элемент во 2ом - 4ом столбце (все края включительно), затем посчитать их произведение

res = B[2:7, 2:5]
print(res)
res.prod()

[[-3 -4  3]
 [ 3  9  4]
 [ 3  8  6]]


559872

In [12]:
# Вывести минимальный и максимальный элемент массива

B.min(), B.max()

(-10, 9)

In [13]:
# Вывести минимальное и максимальное значение в каждом столбце

B.min(0), B.max(0)

(array([ -5,   0,  -3,  -7,  -5, -10,  -9,  -7]),
 array([ 9,  7,  3,  9,  9, -1,  6,  6]))

In [14]:
# Посчитать среднее значение в массиве

B.mean()

0.575

In [15]:
# Вывести значнеие эл-ов больше среднего

B[B > B.mean()]

array([8, 9, 5, 9, 9, 7, 3, 1, 3, 3, 9, 4, 6, 6, 2, 3, 8, 6, 5])

In [16]:
# Вывести матрицу, заменив меньшие нуля эл-ты на ноль

np.clip(B, 0, None)

array([[8, 0, 0, 0, 9, 0, 0, 0],
       [0, 5, 0, 9, 0, 0, 0, 0],
       [9, 7, 0, 0, 3, 0, 0, 0],
       [1, 3, 3, 9, 4, 0, 6, 6],
       [0, 2, 3, 8, 6, 0, 5, 0]])

In [17]:
# Вывести уникальные элементы в массиве и посчитать их кол-во

unique_elems, elems_cnt = np.unique(B, return_counts=True)
unique_elems, elems_cnt

(array([-10,  -9,  -8,  -7,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,
          4,   5,   6,   7,   8,   9]),
 array([1, 1, 1, 3, 3, 1, 3, 3, 1, 4, 1, 1, 4, 1, 2, 3, 1, 2, 4]))

In [18]:
# Вывести самые часто встречающиеся элементы

unique_elems, elems_cnt = np.unique(B, return_counts=True)
most_freq = unique_elems[elems_cnt==elems_cnt.max()]
print(f"Самые часто встречающиеся элементы: {most_freq}")

Самые часто встречающиеся элементы: [0 3 9]


In [19]:
np.random.seed(42)
A = np.random.randint(-10, 10, size=(10, 10))
B = np.random.randint(-10, 10, size=(10, 10))

# Сранить две матрицы - сколько в матрице А элементов больших соотвественных элементов матрицы В

(A > B).sum()

46

In [20]:
np.random.seed(42)
A = np.random.randint(-10, 10, size=(10, 1))
B = np.random.randint(-10, 10, size=(1, 10))

# Попарно перемножить элементы вектора-столбца и вектора-строки и посчитать сумму эл-ов результирующего вектора

res = A*B.T
res.sum()

-167

In [21]:
np.random.seed(42)
A = np.random.randint(-10, 10, size=(10, 1))
B = np.random.randint(-10, 10, size=(1, 10))

# Перемножить две матрицы A и B и посчитать сумму всех элементов матрицы

res=A@B
res.sum()

-105

In [22]:
np.random.seed(42)
C_true = np.random.normal(0, 2, size=(10, 10))
C_with_missings = C_true.copy()
C_with_missings[np.random.binomial(1, 0.1, (C_true.shape)) == 1] = np.nan

# 1) Создать матрицу `C_imputed` и заполнить в ней пропуски средним значением
# 2) Вывести матрицу и посчитать на сколько в среднем отличаются заполненные значения от истиных `C_true`

# SOLUTION:

# 1)
C_imputed = C_with_missings.copy()
mean_value = C_with_missings[~np.isnan(C_with_missings)].mean()
C_imputed[np.isnan(C_imputed)] = mean_value
# 2)
missing_values = C_true[np.isnan(C_with_missings)]
(mean_value - missing_values).mean()

-0.13610629287287748

# Pandas

In [23]:
# импортировать библиотеку `pandas` под псевдонимом `pd`

import pandas as pd

In [24]:
# прочитать данные в переменную `df` из файла '../data/vk_download/vk_main.csv', используя разделитель '\t'

df = pd.read_csv('../data/vk_download/vk_main.csv', sep='\t')

In [25]:
# показать прочитанные колонки датафрейма

df.columns

Index(['city', 'country', 'first_name', 'home_town', 'in_hse_memes_group',
       'is_bmm', 'is_closed', 'last_name', 'likes_memes', 'uid', 'male_dummy',
       'facebook_dummy', 'instagram_dummy', 'skype_dummy', 'twitter_dummy',
       'home_phone_dummy', 'mobile_phone_dummy', 'site_dummy',
       'can_post_dummy', 'can_see_all_posts_dummy', 'can_see_audio_dummy',
       'can_write_private_message_dummy', 'has_mobile_dummy', 'has_ava_dummy',
       'wall_comments_dummy', 'english_dummy', 'folowers_cnt', 'albums_cnt',
       'audio_cnt', 'followers_cnt', 'friends_cnt', 'gifts_cnt', 'groups_cnt',
       'photos_cnt', 'subscriptions_cnt', 'user_photos_cnt', 'videos_cnt',
       'pages_cnt', 'lang_cnt', 'change_city_school_cnt', 'schools_cnt',
       'relation_cat', 'alco_love_cat', 'smoke_love_cat', 'life_main_cat',
       'people_main_cat', 'political_cat', 'private_prof_dummy',
       'wall_can_comment_dummy', 'wall_comment_cnt', 'wall_comment_max',
       'wall_comment_mean', 'wall_co

In [26]:
# вывести тип переменной

type(df)

pandas.core.frame.DataFrame

In [27]:
# вывести типы данных в колонках

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 98 columns):
city                               329 non-null object
country                            365 non-null object
first_name                         426 non-null object
home_town                          113 non-null object
in_hse_memes_group                 426 non-null bool
is_bmm                             426 non-null bool
is_closed                          426 non-null bool
last_name                          426 non-null object
likes_memes                        385 non-null float64
uid                                426 non-null int64
male_dummy                         426 non-null int64
facebook_dummy                     426 non-null int64
instagram_dummy                    426 non-null int64
skype_dummy                        426 non-null int64
twitter_dummy                      426 non-null int64
home_phone_dummy                   426 non-null int64
mobile_phone_dummy         

In [28]:
# Посмотреть в таблице первые 5 строк, а затем последние 3

df.head()
df.tail(3)

city country first_name home_town  in_hse_memes_group  is_bmm  \
423  Ростов-на-Дону  Россия  Александр       NaN                True   False   
424          Москва  Россия       Глеб       NaN                True   False   
425          Москва  Россия      Злата       NaN                True   False   

     is_closed last_name  likes_memes        uid  ...  photo_month_mean  \
423      False  Заривный          3.0  152277289  ...          1.000000   
424      False  Игнатьев        108.0  115455288  ...          2.857143   
425      False    Зимина          6.0  357509100  ...          1.285714   

     photo_repost_cnt  photo_repost_max  photo_repost_mean  \
423               0.0               0.0                0.0   
424               2.0               1.0                0.1   
425               0.0               0.0                0.0   

     photo_repost_median  photo_text_len_cnt  photo_ava_change_cnt  \
423                  0.0                 0.0                   0.0   
424                  0.0                 0.0                   0.0   
425                  0.0                 0.0                   0.0   

     photo_text_url_len_cnt  friends_from_course_cnt  \
423                     0.0                     25.0   
424                     0.0                     12.0   
425                     0.0                     34.0   

     friends_mail_from_course_pct  
423                      0.480000  
424                      0.666667  
425                      0.558824  

[3 rows x 98 columns]

In [29]:
# сколько всего записей в таблице

df.shape[0]

426

In [30]:
# выбрать колонку с городом

df['city']

0              Москва
1              Рязань
2              Москва
3                 NaN
4                 NaN
            ...      
421               NaN
422            Москва
423    Ростов-на-Дону
424            Москва
425            Москва
Name: city, Length: 426, dtype: object

In [31]:
# выбрать колонку с городом, проверить тип возвращаемых данных

type(df['city'])

pandas.core.series.Series

Будьте внимательны, какой тип данных возвращает тот или иной запрос - это `DataFrame` или `Series`

In [32]:
# выбрать след. колонки: имя, фамилия, город

df[['first_name', 'last_name', 'city']]

first_name  last_name            city
0    Александра   Абашкова          Москва
1     Анастасия  Чуфистова          Рязань
2     Александр  Головачев          Москва
3          Анна   Лобанова             NaN
4       Алексей   Пузырный             NaN
..          ...        ...             ...
421        Юлия   Замятина             NaN
422        Илья     Заикин          Москва
423   Александр   Заривный  Ростов-на-Дону
424        Глеб   Игнатьев          Москва
425       Злата     Зимина          Москва

[426 rows x 3 columns]

In [33]:
# Посомтреть, где сейчас живут студенты (уникальные значения колонки city)

df['city'].unique()

array(['Москва', 'Рязань', nan, 'Краснодар', 'Казань', 'Кострома',
       'Санкт-Петербург', 'Хабаровск', 'Пермь', 'Королёв',
       'Железнодорожный (Балашиха)', 'Каракол', 'Минск', 'Екатеринбург',
       'Ташкент', 'Иркутск', 'Madrid', 'Химки', 'Нур-Султан / Астана',
       'Abu Dhabi', 'Заречный', 'Люберцы', 'Североморск', 'Якутск',
       'Запорожье', 'Владикавказ', 'Сочи', 'Красноярск',
       'Нижний Новгород', 'Ростов-на-Дону', 'Белгород', 'Самара',
       'Тюмень', 'Cambridge', 'Азов', 'Омск', 'Киров', 'Воронеж',
       'Петропавловск-Камчатский', 'Сергиев Посад', 'Birmingham',
       'Кишинев', 'Budapest', 'Бишкек', 'Владивосток', 'Новосибирск',
       'Калуга', 'Benidorm', 'Vilamoura', 'Пенза', 'Ярославль',
       'Новомосковск', 'Москва (деревня)', 'Грозный', 'Philadelphia',
       'Новороссийск', 'Дубна'], dtype=object)

In [34]:
# вывести всех студентов, проживающих в Москве (city)

df[df['city'] == 'Москва']

city country  first_name home_town  in_hse_memes_group  is_bmm  \
0    Москва  Россия  Александра    Москва                True   False   
2    Москва  Россия   Александр      Омск               False   False   
5    Москва  Россия  Александер       NaN                True   False   
6    Москва  Россия       Алина       NaN                True   False   
8    Москва  Россия   Anastasia       NaN                True   False   
..      ...     ...         ...       ...                 ...     ...   
419  Москва  Россия       Ясмин       NaN                True   False   
420  Москва  Россия        Паша       NaN                True   False   
422  Москва  Россия        Илья       NaN                True   False   
424  Москва  Россия        Глеб       NaN                True   False   
425  Москва  Россия       Злата       NaN                True   False   

     is_closed      last_name  likes_memes        uid  ...  photo_month_mean  \
0        False       Абашкова         60.0  182152789  ...          1.000000   
2        False      Головачев          0.0  138413935  ...          1.400000   
5        False         Гуляев        104.0  145109161  ...          2.500000   
6        False       Хабирова          6.0  140207230  ...          1.200000   
8        False      Biryukova          0.0   72089509  ...          2.285714   
..         ...            ...          ...        ...  ...               ...   
419      False    Аль-Баргути         10.0  177557939  ...          1.333333   
420      False  Добровольский          2.0  346120308  ...          3.800000   
422      False         Заикин         20.0   74324122  ...          1.400000   
424      False       Игнатьев        108.0  115455288  ...          2.857143   
425      False         Зимина          6.0  357509100  ...          1.285714   

     photo_repost_cnt  photo_repost_max  photo_repost_mean  \
0                 0.0               0.0           0.000000   
2                 0.0               0.0           0.000000   
5                 0.0               0.0           0.000000   
6                 0.0               0.0           0.000000   
8                 2.0               1.0           0.125000   
..                ...               ...                ...   
419               1.0               1.0           0.125000   
420               1.0               1.0           0.026316   
422               1.0               1.0           0.071429   
424               2.0               1.0           0.100000   
425               0.0               0.0           0.000000   

     photo_repost_median  photo_text_len_cnt  photo_ava_change_cnt  \
0                    0.0                 0.0                   0.0   
2                    0.0                 0.0                   0.0   
5                    0.0                 0.0                   0.0   
6                    0.0                 0.0                   0.0   
8                    0.0                 0.0                   0.0   
..                   ...                 ...                   ...   
419                  0.0                 0.0                   0.0   
420                  0.0                 0.0                   0.0   
422                  0.0                 0.0                   0.0   
424                  0.0                 0.0                   0.0   
425                  0.0                 0.0                   0.0   

     photo_text_url_len_cnt  friends_from_course_cnt  \
0                       0.0                     42.0   
2                       0.0                     32.0   
5                       0.0                     29.0   
6                       0.0                     31.0   
8                       0.0                     47.0   
..                      ...                      ...   
419                     0.0                     50.0   
420                     0.0                     23.0   
422                     0.0                     51.0   
424                    

In [35]:
# Заполните пропуски по `city` на значение `Не указано`
# какова доля таких записей?

df['city'] = df['city'].fillna('Не указано')
df[df['city'] == 'Не указано'].shape[0]/df.shape[0]

0.22769953051643194

In [36]:
# посчитать долю пользователей, у которых закрыт профиль - колонка `is_closed`

res = df[df['is_closed']]
frac = res.shape[0]/df.shape[0]
print(f"Доля: {frac:.2%}")
res.head()

Доля: 9.62%


city country first_name home_town  in_hse_memes_group  is_bmm  \
9       Москва  Россия    Николай       NaN                True   False   
15      Москва  Россия        Аня       NaN                True   False   
34   Хабаровск  Россия   Ангелина       NaN                True   False   
71      Москва  Россия      Дарья       NaN                True   False   
73  Не указано  Россия     Полина       NaN                True   False   

    is_closed   last_name  likes_memes        uid  ...  photo_month_mean  \
9        True   Дементьев          NaN  409423465  ...               NaN   
15       True   Никитенко          NaN  183553137  ...               NaN   
34       True    Щетинина          NaN  192630290  ...               NaN   
71       True  Коновалова          NaN  259955111  ...               NaN   
73       True   Садчикова          NaN  277990479  ...               NaN   

    photo_repost_cnt  photo_repost_max  photo_repost_mean  \
9                NaN               NaN                NaN   
15               NaN               NaN                NaN   
34               NaN               NaN                NaN   
71               NaN               NaN                NaN   
73               NaN               NaN                NaN   

    photo_repost_median  photo_text_len_cnt  photo_ava_change_cnt  \
9                   NaN                 NaN                   NaN   
15                  NaN                 NaN                   NaN   
34                  NaN                 NaN                   NaN   
71                  NaN                 NaN                   NaN   
73                  NaN                 NaN                   NaN   

    photo_text_url_len_cnt  friends_from_course_cnt  \
9                      NaN                      NaN   
15                     NaN                      NaN   
34                     NaN                      NaN   
71                     NaN                      NaN   
73                     NaN                      NaN   

    friends_mail_from_course_pct  
9                            NaN  
15                           NaN  
34                           NaN  
71                           NaN  
73                           NaN  

[5 rows x 98 columns]

In [37]:
# Посмотреть 5 случайных записей для пользователей, которые приехали в Москву
# (`home_town` - откуда приехали, 'city' - где живут сейчас)

df[(df['home_town'] != 'Москва') & (df['city'] == 'Москва')].sample(3)

city country first_name home_town  in_hse_memes_group  is_bmm  \
359  Москва  Россия      Мария       NaN                True   False   
155  Москва  Россия   Виктория       NaN                True   False   
81   Москва  Россия        Яна       NaN                True   False   

     is_closed   last_name  likes_memes        uid  ...  photo_month_mean  \
359      False    Назарова         22.0  107770210  ...          4.416667   
155      False  Батрашкина          0.0   84894888  ...          2.727273   
81       False    Варданян          0.0  317626410  ...          1.000000   

     photo_repost_cnt  photo_repost_max  photo_repost_mean  \
359               1.0               1.0           0.018868   
155               0.0               0.0           0.000000   
81                0.0               0.0           0.000000   

     photo_repost_median  photo_text_len_cnt  photo_ava_change_cnt  \
359                  0.0                 0.0                   0.0   
155                  0.0                 0.0                   0.0   
81                   0.0                 0.0                   0.0   

     photo_text_url_len_cnt  friends_from_course_cnt  \
359                     0.0                    106.0   
155                     0.0                     54.0   
81                      0.0                     41.0   

     friends_mail_from_course_pct  
359                      0.490566  
155                      0.333333  
81                       0.365854  

[3 rows x 98 columns]

In [38]:
# Вывести уникальные мужские имена
# пол в столбце `male_dummy`

df.loc[df['male_dummy'] == 1, 'first_name'].unique()

array(['Александр', 'Алексей', 'Александер', 'Николай', 'Danial',
       'Данила', 'Владимир', 'Егор', 'Артём', 'Эдик', 'Георгий',
       'Марсель', 'Глеб', 'Кирилл', 'Данил', 'Рома', 'Никита', 'Артемий',
       'Юрий', 'Максим', 'Иван', 'Иоан', 'Миран', 'New', 'Телубай',
       'Zhao', 'Леонид', 'Роман', 'Даниил', 'Гоша', 'Ислам', 'Карим',
       'Борис', 'Dima', 'Матвей', 'Misha', 'Nikita', 'Нияз', 'Саша',
       'Rayskin', 'Дима', 'Михаил', 'Стёпа', 'Тимур', 'Ованнес', 'Давид',
       'Андрей', 'Антон', 'Тёма', 'Артур', 'Асельдар', 'Вадим', 'Ярослав',
       'Джанкат', 'Алик', 'Дмитрий', 'Ден', 'Ecclesiaste', 'Антанас',
       'Vanya', 'Павел', 'Олег', 'Григорий', 'Рамиз', 'Мурат', 'Артем',
       'Арам', 'Илья', 'Mihail', 'Радомир', 'Арсений', 'Нурали', 'Вова',
       'Ринат', 'Алмаз', 'Пётр', 'Руслан', 'Islam', 'Dominik', 'Иззат',
       'Рахимов', 'Asan', 'Maksim', 'Шерхан', 'Айдар', 'Виталий',
       'Савлат', 'Иннокентий', 'Кубрат', 'Коля', 'Акрам', 'Макс', 'Игорь',
       'Миш

In [39]:
# Найти колонки без единого пропуска

df.columns[df.notnull().all(0)]

Index(['city', 'first_name', 'in_hse_memes_group', 'is_bmm', 'is_closed',
       'last_name', 'uid', 'male_dummy', 'facebook_dummy', 'instagram_dummy',
       'skype_dummy', 'twitter_dummy', 'home_phone_dummy',
       'mobile_phone_dummy', 'site_dummy', 'can_post_dummy',
       'can_see_all_posts_dummy', 'can_see_audio_dummy',
       'can_write_private_message_dummy', 'has_mobile_dummy', 'has_ava_dummy',
       'wall_comments_dummy', 'english_dummy', 'albums_cnt', 'audio_cnt',
       'friends_cnt', 'subscriptions_cnt', 'videos_cnt', 'pages_cnt',
       'private_prof_dummy'],
      dtype='object')

In [40]:
# Вывести 3 самых популярных женских имени среди студентов

(df[df['male_dummy'] == 0]
 .groupby('first_name')
 .count()['uid']
 .sort_values(ascending=False)
 .head(3))

first_name
Дарья        12
Анна         11
Анастасия     9
Name: uid, dtype: int64

In [41]:
# вывести 'uid' самых больших любителей мемов (top 1% значений `likes_memes`)

q = df['likes_memes'].quantile(0.99)
df.loc[df['likes_memes'] >= q,
       ['first_name', 'last_name', 'likes_memes']].sort_values('likes_memes', ascending=False)

first_name last_name  likes_memes
135     Полина  Андреева       1081.0
364     Николь  Пименова        685.0
206  Александр   Поляков        440.0
190      Данил   Астапов        398.0

<span class="mark">TODO</span>: wait for Phillip fix and resolve

In [42]:
# # посчитать соотношение полов в направлениях по маркетингу и менеджменту (`is_bmm` - если с маркетинга 1, с менеджмента 0)

# df[['is_bmm', 'male_dummy']].astype(int).groupby('is_bmm').count().sum()['male_dummy']

In [43]:
# Найти среди двух полов лидера среди тех, кто чаще всего выкладывает фотки
# (среднемесячное кол-во фоток максимальное `photo_month_mean`) вывести
# ФИО и значение параметра `photo_month_mean`

max_male = df.loc[df['male_dummy'] == 1, 'photo_month_mean'].max()
max_female = df.loc[df['male_dummy'] == 0, 'photo_month_mean'].max()
query_filter = (
    (df['male_dummy'] == 0) & (df['photo_month_mean'] == max_female)
    | (df['male_dummy'] == 1) & (df['photo_month_mean'] == max_male)
)
df.loc[query_filter, ['first_name', 'last_name', 'photo_month_mean']]

first_name   last_name  photo_month_mean
197       Алик    Атаханов        131.416667
215       Дуся  Шурмистова        151.833333

In [44]:
# Создать колонку со значением фмаилии и имени через пробел

df['first_last_name'] = df['first_name'] + ' ' + df['last_name']
df['first_last_name']

0      Александра Абашкова
1      Анастасия Чуфистова
2      Александр Головачев
3            Анна Лобанова
4         Алексей Пузырный
              ...         
421          Юлия Замятина
422            Илья Заикин
423     Александр Заривный
424          Глеб Игнатьев
425           Злата Зимина
Name: first_last_name, Length: 426, dtype: object

In [45]:
# Создать колонку со значением фмаилии и имени через пробел

df.columns

Index(['city', 'country', 'first_name', 'home_town', 'in_hse_memes_group',
       'is_bmm', 'is_closed', 'last_name', 'likes_memes', 'uid', 'male_dummy',
       'facebook_dummy', 'instagram_dummy', 'skype_dummy', 'twitter_dummy',
       'home_phone_dummy', 'mobile_phone_dummy', 'site_dummy',
       'can_post_dummy', 'can_see_all_posts_dummy', 'can_see_audio_dummy',
       'can_write_private_message_dummy', 'has_mobile_dummy', 'has_ava_dummy',
       'wall_comments_dummy', 'english_dummy', 'folowers_cnt', 'albums_cnt',
       'audio_cnt', 'followers_cnt', 'friends_cnt', 'gifts_cnt', 'groups_cnt',
       'photos_cnt', 'subscriptions_cnt', 'user_photos_cnt', 'videos_cnt',
       'pages_cnt', 'lang_cnt', 'change_city_school_cnt', 'schools_cnt',
       'relation_cat', 'alco_love_cat', 'smoke_love_cat', 'life_main_cat',
       'people_main_cat', 'political_cat', 'private_prof_dummy',
       'wall_can_comment_dummy', 'wall_comment_cnt', 'wall_comment_max',
       'wall_comment_mean', 'wall_co

In [46]:
# вывести распредление параметров `wall_emoji_cnt` & `wall_comment_cnt`

df[['wall_emoji_cnt','wall_comment_cnt']].hist()

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x117f53110>,
      dtype=object)

In [47]:
# 1) создать колонку `wall_emoji_vs_comments` как отношение
# кол-ва эмодзи `wall_emoji_cnt` к кол-ву комментариев `wall_comment_cnt` на стене,
# 2) по показателю отобрать топ15 юзеров и вывести их (имя фамилия, пол, расчитанный показатель)
# 3) кого там больше - парней или девушек (посчитайте долю девушек)?
# ! в колонках бывают нули и пропуски, помните о этом


# один из вариантов посчитать такой показатель
# альтернативно можно пофильтровать нули и пропуски
df['wall_emoji_vs_comments'] = (df['wall_emoji_cnt'].fillna(0) 
                                / (df['wall_comment_cnt']+1)).fillna(0)
res = (df
       .sort_values('wall_emoji_vs_comments', ascending=False)
       .reset_index()
       .loc[:15, ['first_last_name', 'male_dummy', 'wall_emoji_vs_comments']])

male_frac = 1 - res['male_dummy'].sum()/res.shape[0]
print(f"Доля девушек: {male_frac}")
res

Доля девушек: 0.625


first_last_name  male_dummy  wall_emoji_vs_comments
0   Григорий Черноусов           1                  1914.0
1         Юлия Иванова           0                  1904.0
2         Оля Федотова           0                   751.0
3      Дуся Шурмистова           0                   737.0
4       Тимур Минибаев           1                   402.0
5      Дарья Кухаренко           0                   309.0
6        Диана Геличук           0                   306.0
7      Андрей Гладышев           1                   239.0
8        Сандрик Кецба           1                   223.0
9        Соня Суханова           0                   213.0
10  Александр Заривный           1                   199.0
11       Анна Билялова           0                   178.0
12         Арина Мишак           0                   167.0
13        Дима Руденко           1                   157.0
14       Катя Фомичева           0                   151.0
15        Дарья Орлова           0                   129.0